{"name": "Проверка авторизации пользователем с неверным паролем", "status": "passed", "start": 1719861623962, "stop": 1719861624299, "uuid": "d68b89ff-49de-43e8-a55f-7e12481374e3", "historyId": "b1989d319aef0a9eec9347f59afe5406", "testCaseId": "b1989d319aef0a9eec9347f59afe5406", "fullName": "tests.test_user_authentication.TestLoginUser#test_login_user_incorrect_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-6FRR489"}, {"name": "thread", "value": "14572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}