{"name": "Проверка авторизации пользователем с неверным паролем", "status": "passed", "start": 1720555321468, "stop": 1720555321701, "uuid": "cbbb4beb-d2c5-4c96-8f66-0eb80d3bf054", "historyId": "b1989d319aef0a9eec9347f59afe5406", "testCaseId": "b1989d319aef0a9eec9347f59afe5406", "fullName": "tests.test_user_authentication.TestLoginUser#test_login_user_incorrect_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-6FRR489"}, {"name": "thread", "value": "2940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}