{"name": "Проверка авторизации пользователем", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <tests.test_user_authentication.TestLoginUser object at 0x000001AD7B1F7170>, create_user = {'login_pass': [], 'response': <Response [403]>}\n\n    @allure.title('Проверка авторизации пользователем')\n    def test_login_user(self, create_user):\n        payload = {\n>           \"email\":  create_user['login_pass'][0],\n            \"password\": create_user['login_pass'][1],\n        }\nE       IndexError: list index out of range\n\ntests\\test_user_authentication.py:47: IndexError"}, "start": 1719861604743, "stop": 1719861604743, "uuid": "2d66c2fa-588b-4bf1-b42e-b84e4a0297b0", "historyId": "f163ce2a64363a5cf10e7adb2af2ba41", "testCaseId": "f163ce2a64363a5cf10e7adb2af2ba41", "fullName": "tests.test_user_authentication.TestLoginUser#test_login_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-6FRR489"}, {"name": "thread", "value": "16736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}